# Generated by Django 4.1 on 2023-03-27 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
