# Generated by Django 4.1 on 2023-03-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='celular',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='usuario',
            new_name='username',
        ),
    ]
