# Generated by Django 4.1 on 2023-04-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0002_rename_mail_registro_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=40)),
                ('celular', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=15)),
                ('provincia', models.CharField(max_length=15)),
                ('info_adicional', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
